spring.application.name=backend
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.hibernate.ddl-auto=validate
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8081/realms/cultural-events
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://keycloak:8080/realms/cultural-events/protocol/openid-connect/certs